NAME := solidity
DEPENDS_ON := \
	vscode
CODE_EXTENSIONS := \
	RemixProject.ethereum-remix \

include $(CODY)
include $(SHARED)/code/code.mk

.PHONY: install
install: code-extensions

.PHONY: uninstall
uninstall:
