NAME := debian
DEPENDS_ON := \
	vscode
CODE_EXTENSIONS := \
	dawidd6.debian-vscode \

include $(CODY)
include $(SHARED)/code/code.mk

.PHONY: install
install: code-extensions

.PHONY: uninstall
uninstall:
